# Generated by Django 4.1.2 on 2022-11-22 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название чата')),
                ('description', models.TextField(blank=True, verbose_name='Описание чата')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
        migrations.CreateModel(
            name='ChatMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Статус участника в чате')),
                ('chat', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chats.chat', verbose_name='Чат, в котором состоит пользователь')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(verbose_name='Текст сообщения')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания сообщения')),
                ('read_status', models.BooleanField(default=False, verbose_name='Статус прочтения сообщения')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='chats.chatmember', verbose_name='Отправитель сообщения')),
                ('chat', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.chat', verbose_name='Чат, в котором находится сообщение')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
