# Generated by Django 4.1.2 on 2022-10-31 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_birthday'),
        ('chats', '0003_alter_chat_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Чат'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user_id',
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chats.chat', verbose_name='Чат, в котором находится сообщение'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user', verbose_name='Отправитель сообщения'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание чата'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название чата'),
        ),
        migrations.AlterField(
            model_name='message',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания сообщения'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
    ]
