# Generated by Django 4.1.2 on 2022-11-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_chat_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read_status',
            field=models.BooleanField(default=False, verbose_name='Статус прочтения сообщения'),
        ),
    ]
