# Generated by Django 4.1.2 on 2022-11-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_chatmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmember',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Статус участника в чате'),
        ),
    ]
