# Generated by Django 4.1.2 on 2022-10-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True)),
                ('chats', models.ManyToManyField(to='chats.chat')),
            ],
        ),
    ]
