# Generated by Django 4.1.2 on 2022-10-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_chat_options_alter_message_options_and_more'),
        ('users', '0002_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь'},
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='chats',
            field=models.ManyToManyField(to='chats.chat', verbose_name='Чаты пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=200, verbose_name='Имя пользователя'),
        ),
    ]
